---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# fqacalc

## A Florisitic Quality Assessment Calculator for R

<!-- badges: start -->
<!-- badges: end -->

This package provides functions for calculating floristic quality metrics based on the 47 regional FQA databases which have been approved for use by the US Army Core of Engineers. 

## Installation

You can install the development version of fqacalc from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ifoxfoot/fqacalc")
```

## Example

```{r example}
#load the package
library(fqacalc)

#the package comes with an example site assessment from crooked island, MI
head(crooked_island)

#here is an example of all metrics wrapped into one function
all_metrics(crooked_island, key = "acronym", db = "michigan_2014")
```

